package com.project.alm


enum KpiLifeCycleStage {

    PIPELINE_STARTED("PIPELINE_STARTED"),
    PIPELINE_FINISHED("PIPELINE_FINISHED"),
    BUILD_STARTED("BUILD_STARTED"),
    BUILD_FINISHED("BUILD_FINISHED"),
	DEPLOY_STARTED("DEPLOY_STARTED"),
    DEPLOY_FINISHED("DEPLOY_FINISHED"),
	IT_TEST_STARTED("IT_TEST_STARTED"),
    IT_TEST_FINISHED("IT_TEST_FINISHED"),
    ERROR_MANAGEMENT_PUBLISH_STARTED("ERROR_MANAGEMENT_PUBLISH_STARTED"),
    ERROR_MANAGEMENT_PUBLISH_ENDED("ERROR_MANAGEMENT_PUBLISH_ENDED"),
    ERROR_MANAGEMENT_PUBLISH_ERROR("ERROR_MANAGEMENT_PUBLISH_ERROR"),
	DEPROVISIONING_STARTED("DEPROVISIONING_STARTED"),
	DEPROVISIONING_FINISHED("DEPROVISIONING_FINISHED"),
	DEPROVISIONING_ERROR("DEPROVISIONING_ERROR"),
    PROVISIONING_STARTED("PROVISIONING_STARTED"),
    PROVISIONING_FINISHED("PROVISIONING_FINISHED"),
    CREATE_RELEASE_STARTED("CREATE_RELEASE_STARTED"),
    CREATE_RELEASE_FINISHED("CREATE_RELEASE_FINISHED"),
    HOTFIX_CREATION_STARTED("HOTFIX_CREATION_STARTED"),
    HOTFIX_CREATION_FINISHED("HOTFIX_CREATION_FINISHED"),
    INCREASE_CANARY_$_STARTED("INCREASE_CANARY_\$_STARTED"),
    INCREASE_CANARY_$_FINISHED("INCREASE_CANARY_\$_FINISHED"),
    CLOSE_STARTED("CLOSE_STARTED"),
    CLOSE_FINISHED("CLOSE_FINISHED")


    private String name;

    private KpiLifeCycleStage(String s) {
        name = s;
    }

    boolean equalsName(String other) {
        return name.equals(other);
    }

    static KpiLifeCycleStage valueOfKpiLifeCycleStages(String other) {
        values().find { it.name == other }
    }

    String asString() {
        return name
    }
}

